# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 01:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0004_subject_coursecode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.TextField(verbose_name='justification')),
                ('ntnuSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ntnuSubject', to='subjects.Subject', verbose_name=b'NTNU subject')),
                ('replacingSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacingSubject', to='subjects.Subject', verbose_name=b'replacing subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'user')),
            ],
        ),
    ]
