# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 13:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_auto_20170312_1339'),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='ntnuSubject',
        ),
        migrations.RemoveField(
            model_name='application',
            name='replacingSubject',
        ),
        migrations.AddField(
            model_name='application',
            name='ntnu_subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ntnuSubject', to='subjects.Subject', verbose_name='NTNU subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='replacing_subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='replacingSubject', to='subjects.Subject', verbose_name='replacing subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
