# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_application_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Processing', max_length=20),
        ),
    ]
