# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='ntnuCredits',
            field=models.DecimalField(decimal_places=2, default=7.5, max_digits=5, verbose_name='ntnuCredits'),
            preserve_default=False,
        ),
    ]
