# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_auto_20170303_1839'),
        ('subjects', '0002_subject_ntnucredits'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='university',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='universities.University', verbose_name=b'university'),
            preserve_default=False,
        ),
    ]
