# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_subject_coursecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='courseCode',
            field=models.CharField(max_length=20, verbose_name='course code'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='ntnuCredits',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='ntnuCredits'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.University'),
        ),
    ]
